version: '3.8'

services:
  db:
    image: harbor.tteam.dev/orig/postgres:14.4-alpine3.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
#      - ./data:/var/lib/postgresql/data:rw
      - ./scripts/database/:/docker-entrypoint-initdb.d
    ports:
    - "5432:5432"
    init: true

  service:
    image: docker.io/akaddr/net:v0.1.0
    ports:
      - "8000:8000"
