version: '3.8'

services:
  db:
    image: postgres:14.11-alpine3.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
#      - ./data:/var/lib/postgresql/data:rw
      - ./scripts/database/:/docker-entrypoint-initdb.d
    ports:
    - "5432:5432"
    init: true
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  service:
    image: docker.io/akaddr/net:v0.2.0
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
