/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"github.com/xpoh/otus-work/internal/config"
	"github.com/xpoh/otus-work/internal/database"
)

type Instance struct {
	db  *database.Instance
	rds *redis.Client
	cfg *config.Config

	usersOnline map[string]any
}

func NewInstance(db *database.Instance, cfg *config.Config) *Instance {
	r := redis.NewClient(&redis.Options{
		Addr: fmt.Sprintf("%s:%d", cfg.GetRedisHost(), cfg.GetRedisPort()),
	})

	return &Instance{
		db:          db,
		rds:         r,
		cfg:         cfg,
		usersOnline: make(map[string]any),
	}
}

// DialogUserIdListGet Get /dialog/:user_id/list
func (i *Instance) DialogUserIdListGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// DialogUserIdSendPost Post /dialog/:user_id/send
func (i *Instance) DialogUserIdSendPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
