/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
	"github.com/xpoh/otus-work/internal/config"
	"github.com/xpoh/otus-work/internal/database"
)

type Instance struct {
	db  *database.Instance
	cfg *config.Config
}

func NewInstance(db *database.Instance, cfg *config.Config) *Instance {
	return &Instance{
		db:  db,
		cfg: cfg,
	}
}

// DialogUserIdListGet Get /dialog/:user_id/list
func (i *Instance) DialogUserIdListGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// DialogUserIdSendPost Post /dialog/:user_id/send
func (i *Instance) DialogUserIdSendPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
