/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserRegisterPostRequest struct {
	FirstName string `json:"first_name,omitempty"`

	SecondName string `json:"second_name,omitempty"`

	// Дата рождения
	Birthdate string `json:"birthdate,omitempty"`

	Biography string `json:"biography,omitempty"`

	City string `json:"city,omitempty"`

	Password string `json:"password,omitempty"`
}
