/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type User struct {
	// Идентификатор пользователя
	Id string `json:"id,omitempty"`

	// Имя
	FirstName string `json:"first_name,omitempty"`

	// Фамилия
	SecondName string `json:"second_name,omitempty"`

	// Дата рождения
	Birthdate string `json:"birthdate,omitempty"`

	// Интересы
	Biography string `json:"biography,omitempty"`

	// Город
	City string `json:"city,omitempty"`
}
