/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type DialogMessage struct {
	// Идентификатор пользователя
	From string `json:"from"`

	// Идентификатор пользователя
	To string `json:"to"`

	// Текст сообщения
	Text string `json:"text"`
}
