scripts/config --enable CONFIG_SECURITY_SELINUX
scripts/config --enable CONFIG_SECURITY_SMACK
scripts/config --enable CONFIG_SECURITY_TOMOYO
scripts/config --enable CONFIG_SECURITY_APPARMOR
scripts/config --enable CONFIG_SECURITY_YAMA
scripts/config --enable CONFIG_RANDOMIZE_BASE
scripts/config --enable CONFIG_CPU_MITIGATIONS
scripts/config --enable CONFIG_MITIGATION_SPECTRE_BHI
scripts/config --enable CONFIG_MITIGATION_RFDS
scripts/config --enable CONFIG_PAGE_TABLE_ISOLATION
scripts/config --enable CONFIG_ZSWAP
scripts/config --enable CONFIG_BPF
scripts/config --enable CONFIG_BPF_SYSCALL
scripts/config --enable CONFIG_BPF_JIT
scripts/config --enable CONFIG_BPF_EVENTS
scripts/config --enable CONFIG_BPFILTER
scripts/config --enable CONFIG_DEBUG_FS
scripts/config --enable CONFIG_FTRACE
scripts/config --enable CONFIG_FUNCTION_TRACER
scripts/config --enable CONFIG_DYNAMIC_FTRACE
scripts/config --enable CONFIG_FUNCTION_GRAPH_TRACER
scripts/config --enable CONFIG_STACK_TRACER
scripts/config --enable CONFIG_KUNIT
scripts/config --enable CONFIG_KUNIT_TEST
scripts/config --enable CONFIG_KASAN
scripts/config --enable CONFIG_STACKTRACE
scripts/config --enable CONFIG_KASAN_GENERIC
scripts/config --enable CONFIG_KASAN_INLINE
scripts/config --enable CONFIG_KASAN_EXTRA_INFO
scripts/config --enable CONFIG_KGDB
scripts/config --enable CONFIG_KGDB_SERIAL_CONSOLE
scripts/config --enable CONFIG_DEBUG_INFO
scripts/config --enable CONFIG_SERIAL_CONSOLE
scripts/config --enable CONFIG_CONSOLE_POLL
scripts/config --enable CONFIG_KPROBES
scripts/config --enable CONFIG_KPROBE_EVENT
scripts/config --disable BASE_SMALL
scripts/config --disable FB_BACKLIGHT
scripts/config --disable HYPERV
scripts/config --disable ANDROID_BINDER_IPC
scripts/config --disable ANDROID_BINDERFS
scripts/config --disable CRYPTO_LIB_CURVE25519_GENERIC
scripts/config --disable CRYPTO_LIB_POLY1305_GENERIC
scripts/config --disable BOOTPARAM_HUNG_TASK_PANIC
scripts/config --disable SYSTEM_TRUSTED_KEYS
scripts/config --disable SYSTEM_REVOCATION_KEYS
scripts/config --disable MODULE_SIG
scripts/config --disable MODULE_SIG_ALL
scripts/config --disable MODULE_SIG_FORCE
scripts/config --disable CONFIG_DEBUG_INFO_NONE
