/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct{}

// DialogUserIdListGet Get /dialog/:user_id/list
func (api *DefaultAPI) DialogUserIdListGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// DialogUserIdSendPost Post /dialog/:user_id/send
func (api *DefaultAPI) DialogUserIdSendPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// FriendDeleteUserIdPut Put /friend/delete/:user_id
func (api *DefaultAPI) FriendDeleteUserIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// FriendSetUserIdPut Put /friend/set/:user_id
func (api *DefaultAPI) FriendSetUserIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// LoginPost Post /login
func (api *DefaultAPI) LoginPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostCreatePost Post /post/create
func (api *DefaultAPI) PostCreatePost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostDeleteIdPut Put /post/delete/:id
func (api *DefaultAPI) PostDeleteIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostFeedGet Get /post/feed
func (api *DefaultAPI) PostFeedGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostGetIdGet Get /post/get/:id
func (api *DefaultAPI) PostGetIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostUpdatePut Put /post/update
func (api *DefaultAPI) PostUpdatePut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// UserGetIdGet Get /user/get/:id
func (api *DefaultAPI) UserGetIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// UserRegisterPost Post /user/register
func (api *DefaultAPI) UserRegisterPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// UserSearchGet Get /user/search
func (api *DefaultAPI) UserSearchGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
