/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"github.com/gin-gonic/gin"
	"github.com/xpoh/otus-work/internal/config"
	"github.com/xpoh/otus-work/internal/database"
)

type Instance struct {
	db  *database.Instance
	cfg *config.Config
}

func NewInstance(db *database.Instance, cfg *config.Config) *Instance {
	return &Instance{
		db:  db,
		cfg: cfg,
	}
}

// DialogUserIdListGet Get /dialog/:user_id/list
func (api *Instance) DialogUserIdListGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// DialogUserIdSendPost Post /dialog/:user_id/send
func (api *Instance) DialogUserIdSendPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// FriendDeleteUserIdPut Put /friend/delete/:user_id
func (api *Instance) FriendDeleteUserIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// FriendSetUserIdPut Put /friend/set/:user_id
func (api *Instance) FriendSetUserIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// LoginPost Post /login
func (api *Instance) LoginPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostCreatePost Post /post/create
func (api *Instance) PostCreatePost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostDeleteIdPut Put /post/delete/:id
func (api *Instance) PostDeleteIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostFeedGet Get /post/feed
func (api *Instance) PostFeedGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostGetIdGet Get /post/get/:id
func (api *Instance) PostGetIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// PostUpdatePut Put /post/update
func (api *Instance) PostUpdatePut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// UserGetIdGet Get /user/get/:id
func (api *Instance) UserGetIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// UserRegisterPost Post /user/register
func (api *Instance) UserRegisterPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// UserSearchGet Get /user/search
func (api *Instance) UserSearchGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
