/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PostUpdatePutRequest struct {
	// Идентификатор поста
	Id string `json:"id"`

	// Текст поста
	Text string `json:"text"`
}
