{
 "title": "Kprobe Traffic",
 "tags": [
  "kprobe",
  "traffic"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tracked Sessions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kprobe_traffic_stats_top_addrs_scrape_count"
    }
   ]
  },
  {
   "title": "Top 10 Sessions by Traffic (Recv)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kprobe_traffic_stats_traffic_recv_bytes",
     "legendFormat": "recv {{src_ip}} → {{dst_ip}}"
    }
   ]
  },
  {
   "title": "Top 10 Sessions by Traffic (Send)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kprobe_traffic_stats_traffic_send_bytes",
     "legendFormat": "send {{src_ip}} → {{dst_ip}}"
    }
   ]
  },
  {
   "title": "Total Traffic (bytes)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kprobe_traffic_stats_traffic_recv_bytes) + sum(kprobe_traffic_stats_traffic_send_bytes)"
    }
   ]
  },
  {
   "title": "Top 10 Sessions by Traffic (Recv)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kprobe_traffic_stats_traffic_recv_bytes[$__interval])",
     "legendFormat": "recv {{src_ip}} → {{dst_ip}}"
    }
   ]
  },
  {
   "title": "Top 10 Sessions by Traffic (Send)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kprobe_traffic_stats_traffic_send_bytes[$__interval])",
     "legendFormat": "recv {{src_ip}} → {{dst_ip}}"
    }
   ]
  }
 ]
}